### ISSUE TITLE
我在这里提issue，你能看到吗

### ISSUE THREAD

**Issue by AlexanderMC8533** [zhuchunshu/CodeFec#3]
站长手撸论坛真牛逼

**Comment by zhuchunshu** [comment]
可以的，但是这个项目已经不再更新维护了
请关注重构版:[https://github.com/zhuchunshu/super-forum](https://github.com/zhuchunshu/super-forum)

**Comment by AlexanderMC8533** [comment]
原来在这里
我可能跟不上节奏了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月25日(周三) 上午9:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zhuchunshu/CodeFec] 我在这里提issue，你能看到吗 (#3)




 
可以的，但是这个项目已经不再更新维护了
 请关注重构版:https://github.com/zhuchunshu/super-forum
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
